In [1]:
import torch

In [2]:
a = torch.tensor(list(range(9)))

In [3]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a.size()

torch.Size([9])

In [5]:
a.storage_offset()

0

In [6]:
a.stride()

(1,)

In [7]:
b = a.view(3,3)

In [8]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
b.size()

torch.Size([3, 3])

In [10]:
b.storage_offset()

0

In [11]:
b.stride()

(3, 1)

In [12]:
id(a.untyped_storage()) == id(b.untyped_storage())

True

In [13]:
c = b[1:, 1:]

In [14]:
c

tensor([[4, 5],
        [7, 8]])

In [15]:
c.storage_offset()

4

In [16]:
c.size()

torch.Size([2, 2])

In [17]:
c.stride()

(3, 1)