In [1]:
import torch

In [2]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [3]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
a = torch.ones(3)

In [5]:
a

tensor([1., 1., 1.])

In [6]:
a[0]

tensor(1.)

In [7]:
float(a[0])

1.0

In [8]:
a[2] = 2.0

In [9]:
a

tensor([1., 1., 2.])

## The essence of Tensors

In [10]:

#representing a triangle using three points using tensors

points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0


In [11]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [13]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [14]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [16]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points.shape

torch.Size([3, 2])

In [18]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
points[0,0] = 5.0

In [20]:
points

tensor([[5., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points[2,1] = 10.0

In [22]:
points

tensor([[ 5.,  1.],
        [ 5.,  3.],
        [ 2., 10.]])

In [23]:
points[0]

tensor([5., 1.])

## Indexing Tensors

In [24]:
points

tensor([[ 5.,  1.],
        [ 5.,  3.],
        [ 2., 10.]])

In [25]:
points[1:]

tensor([[ 5.,  3.],
        [ 2., 10.]])

In [26]:
points[1:, 0]

tensor([5., 2.])

In [27]:
# this adds a dimension of size 1, just like unsqueeze
points[None] 

tensor([[[ 5.,  1.],
         [ 5.,  3.],
         [ 2., 10.]]])

In [28]:
points.shape

torch.Size([3, 2])

In [29]:
points[None].shape

torch.Size([1, 3, 2])

## Named Tensors

### Problem with unnamed tensors

In [30]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [31]:
batch_t = torch.randn(2, 3, 5, 5)

In [32]:
img_t.shape

torch.Size([3, 5, 5])

In [33]:
batch_t.shape

torch.Size([2, 3, 5, 5])

In [34]:
img_t.mean(-3)

tensor([[-0.6071,  0.8489, -0.2893,  0.0878,  1.1609],
        [ 0.3226,  0.3500, -0.8042, -0.6069, -0.5809],
        [ 0.1942,  0.3179, -0.0983,  0.3349, -0.1960],
        [ 0.1731, -0.5671,  0.5369, -0.0468, -0.8363],
        [-0.5534,  0.3358,  0.3065,  0.3206, -0.3329]])

In [35]:
batch_t.mean(-3)

tensor([[[-0.4072, -0.0638, -0.1919,  0.2581,  0.1287],
         [ 0.3594,  0.7438,  0.2285, -0.3491, -0.8795],
         [-0.4737,  0.1090, -0.6899, -0.3977, -0.7098],
         [ 0.1478,  1.2751, -0.9678, -0.3355,  0.0236],
         [-0.5022,  0.1262,  0.0897, -0.8611, -0.3306]],

        [[-0.2869, -0.0540,  0.7468, -0.6129,  0.0278],
         [-0.1192, -0.7541, -0.2604, -0.2786, -0.0401],
         [-0.1200, -0.0573,  0.7873,  0.2349, -0.6730],
         [ 0.9490, -0.7578, -0.2667,  0.7276, -0.3799],
         [-0.2657,  0.2919,  0.1153,  0.2924, -0.9056]]])

In [36]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [37]:
unsqueeze_weights = weights.unsqueeze(-1).unsqueeze(-1)

In [38]:
unsqueeze_weights.shape

torch.Size([3, 1, 1])

In [39]:
img_t.shape

torch.Size([3, 5, 5])

In [40]:
unsqueeze_weights.shape

torch.Size([3, 1, 1])

In [41]:
img_weights = img_t * unsqueeze_weights

In [42]:
batch_weights = batch_t * unsqueeze_weights

In [43]:
img_weights.shape

torch.Size([3, 5, 5])

In [44]:
img_gray_weighted = img_weights.mean(-3)

In [45]:
batch_gray_weighted = batch_weights.mean(-3)

In [46]:
batch_gray_weighted.shape

torch.Size([2, 5, 5])

In [47]:
img_gray_weighted

tensor([[-3.3827e-01,  4.0374e-01, -2.7028e-02,  6.0135e-02,  1.4355e-01],
        [-2.6614e-02,  2.2627e-02, -4.0972e-01, -2.7174e-01, -3.9620e-01],
        [ 1.8223e-02, -6.4909e-03, -7.5404e-02, -3.2924e-02, -3.0131e-01],
        [-4.2192e-03, -3.0391e-01,  4.7924e-01,  2.6857e-01, -3.3472e-01],
        [-6.1290e-02,  1.8861e-04,  1.8128e-01,  1.8338e-01, -1.3314e-01]])

### Solutions with named tensors

In [48]:
img_named = img_t.refine_names(...,'channels','rows', 'columns')
batch_named = batch_t.refine_names(...,'channels','rows', 'columns')

/home/fm-pc-lt-278/.local/lib/python3.10/site-packages/torch/_tensor.py:1122: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1788.)
  return super().refine_names(names)


In [49]:
img_named.shape, img_named.names

(torch.Size([3, 5, 5]), ('channels', 'rows', 'columns'))

In [50]:
batch_named.shape, batch_named.names

(torch.Size([2, 3, 5, 5]), (None, 'channels', 'rows', 'columns'))

In [51]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])

In [52]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [53]:
weights_aligned = weights_named.align_as(img_named)

In [54]:
weights_aligned.shape

torch.Size([3, 1, 1])

In [55]:
gray_named = (img_named * weights_aligned).sum('channels')

In [56]:
gray_named

tensor([[-1.0148e+00,  1.2112e+00, -8.1083e-02,  1.8041e-01,  4.3066e-01],
        [-7.9841e-02,  6.7880e-02, -1.2292e+00, -8.1521e-01, -1.1886e+00],
        [ 5.4668e-02, -1.9473e-02, -2.2621e-01, -9.8772e-02, -9.0393e-01],
        [-1.2657e-02, -9.1174e-01,  1.4377e+00,  8.0570e-01, -1.0042e+00],
        [-1.8387e-01,  5.6584e-04,  5.4385e-01,  5.5013e-01, -3.9941e-01]],
       names=('rows', 'columns'))

## Managing Tensors dtype attribute

In [57]:
double_points = torch.ones(10,2, dtype=torch.double)

In [58]:
double_points.dtype

torch.float64

In [59]:
short_points = torch.tensor([[2,3],[2,5]], dtype=torch.short)

In [60]:
short_points.dtype

torch.int16

In [61]:
torch.zeros(2).double()

tensor([0., 0.], dtype=torch.float64)

In [62]:
torch.get_num_threads()

8

## Indexing into Storage

In [63]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [64]:
points.storage()

/tmp/ipykernel_100636/2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()
/home/fm-pc-lt-278/.local/lib/python3.10/site-packages/IPython/lib/pretty.py:778: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/home/fm-pc-lt-278/.local/lib/python3.10/site-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly. 

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [65]:
points_storage = points.storage()

/tmp/ipykernel_100636/3231221392.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()


In [66]:
points_storage[0]

/tmp/ipykernel_100636/4210428405.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0]


4.0

In [67]:
points_storage[0] = 100.0


/tmp/ipykernel_100636/2426840409.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0] = 100.0


In [68]:
points

tensor([[100.,   1.],
        [  5.,   3.],
        [  2.,   1.]])

## Views of another tensor's storage

In [69]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [70]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [71]:
second_point = points[1]

In [72]:
second_point

tensor([5., 3.])

In [73]:
second_point.storage_offset()

2

In [74]:
second_point.size()

torch.Size([2])

## Transposing without copying

In [80]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [81]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [83]:
id(points.untyped_storage()) == id(points_t.untyped_storage())

True

In [85]:
points.stride()

(2, 1)

In [86]:
points_t.stride()

(1, 2)

## Transposing in Higher Dimensions

In [87]:
some_t = torch.ones(3,4,5)

In [88]:
transpose_t = some_t.transpose(0,2)

In [90]:
some_t.shape

torch.Size([3, 4, 5])

In [91]:
transpose_t.shape

torch.Size([5, 4, 3])

In [92]:
some_t.stride()

(20, 5, 1)

In [93]:
transpose_t.stride()

(1, 5, 20)

## Contiguous

In [94]:
points.is_contiguous()

True

In [95]:
points_t.is_contiguous()

False

In [96]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [97]:
points_t_cont.storage()

/tmp/ipykernel_100636/1562932398.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_t_cont.storage()
/home/fm-pc-lt-278/.local/lib/python3.10/site-packages/IPython/lib/pretty.py:778: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/home/fm-pc-lt-278/.local/lib/python3.10/site-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages dir

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [98]:
points_t_cont.stride()

(3, 1)

## View

In [99]:
x = torch.randn(4,4)

In [100]:
x

tensor([[-0.6393,  0.1223, -2.0079, -0.5731],
        [-0.4355,  0.7205,  0.0435, -0.4956],
        [-1.5550, -0.8268, -0.8178, -0.3450],
        [-1.1393,  1.1105, -1.8452,  0.3907]])

In [102]:
x.size()

torch.Size([4, 4])

In [103]:
x.shape

torch.Size([4, 4])

In [104]:
x.view(16)

tensor([-0.6393,  0.1223, -2.0079, -0.5731, -0.4355,  0.7205,  0.0435, -0.4956,
        -1.5550, -0.8268, -0.8178, -0.3450, -1.1393,  1.1105, -1.8452,  0.3907])

In [105]:
x.view(2,8)

tensor([[-0.6393,  0.1223, -2.0079, -0.5731, -0.4355,  0.7205,  0.0435, -0.4956],
        [-1.5550, -0.8268, -0.8178, -0.3450, -1.1393,  1.1105, -1.8452,  0.3907]])

## Managing a tensor's device attribute

In [106]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [107]:
points_gpu = points.to(device='cuda')

In [108]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')